config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'sessions#new'

  delete 'sign_out' => 'sessions#destroy'
  post   'sign_in'  => 'sessions#create'
  get    'sign_in'  => 'sessions#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :fullname,
            presence: true,
            length: { maximum: 50 }
  
  validates :password,
            presence: true,
            length: { minimum: 8 }

  validates :email,
            presence: true,
            format: { with: URI::MailTo::EMAIL_REGEXP },
            uniqueness: { case_sensitive: false },
            length: { maximum: 260}

  before_save { self.email = email.downcase }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def authorize
    unless logged_in?
      redirect_to root_url
    end
  end

  def correct_user?
    @user = User.find(params[:id])
    unless current_user == @user
      redirect_to users_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :block_access, except: [:destroy]

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      sign_in @user 
      redirect_to @user
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:new, :create]
  before_action :correct_user?, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to @user, notice: "Usuário criado com sucesso"
      sign_in @user
    else
      render action: :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = @user = User.find(params[:id])
    return redirect_to users_path if @user.update_attributes(user_params)
    render action: :edit
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    sign_out
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user)
      .permit(:fullname,
              :cpf,
              :nickname,
              :active,
              :email,
              :password,
              :password_confirmation
            )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def block_access
    redirect_to users_path if current_user.present?
  end

  def logged_in?
    !current_user.nil?
  end

  def sign_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <div>
    <nav>
      <ul>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li>
            <ul>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li>
                <%= link_to "Log out", sign_out_path, method: "delete" %>
              </li>
            </ul>
          </li>
          <li><%= link_to "Settings",
            edit_user_path(current_user) %>
          </li>
        <% else %>
          <li><%= link_to "Log in", root_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RogasKingdomVue</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert-error">
        O formulário contém <%= pluralize(@user.errors.count, "erro") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :fullname %>
    <%= f.text_field :fullname %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Cadastrar"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1><%= User Settings %></h1>
<%= render 'form' %>
<ul>
  <li><%= link_to "Edit", edit_user_path(current_user) %></li>
  <li><%= link_to "Delete", @user, method: :delete%></li>
</ul>

app/views/users/index.html.erb
<h1> Users </h1>
 <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.fullname %></td>
          <td><%= user.email %></td>
          <td><%= link_to "Show", user %></td>
        </tr>
     <%end%>
   </tbody>
</table>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<html>
  <body>
    <h3> Perfil de <%= @user.fullname %> </h3>
    <%= @user.email %>
    <% if current_user == @user %>
      <ul>
        <li><%= link_to "Edit", edit_user_path(current_user) %></li>
        <li><%= link_to "Delete", @user, method: :delete%></li>
      </ul>
    <%end%>
  </body>
</html>